import { PlaceHolderImages } from './placeholder-images';
import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Anillo de Oro Clásico',
    price: 1200,
    description: 'Un impresionante collar de jade verde, elaborado en oro de 18k. Un símbolo atemporal de elegancia.',
    image: PlaceHolderImages.find(p => p.id === 'product-ring-1')!,
    category: 'Rings',
    rating: 4,
    reviews: 124,
  },
  {
    id: '2',
    name: 'Anillo de Oro con Diamantes',
    price: 2500,
    originalPrice: 3000,
    description: 'Un delicado par de aretes de jade ovalados con detalles de diamantes.',
    image: PlaceHolderImages.find(p => p.id === 'product-earrings-1')!,
    category: 'Rings',
    rating: 5,
    reviews: 89,
  },
  {
    id: '3',
    name: 'Anillo de Oro Moderno',
    price: 950,
    description: 'Elegante pulsera de perlas de agua dulce, perfecta para añadir un toque de sofisticación clásica.',
    image: PlaceHolderImages.find(p => p.id === 'product-bracelet-1')!,
    category: 'Rings',
    rating: 5,
    reviews: 210,
  },
  {
    id: '4',
    name: 'Anillo de Oro Vintage',
    price: 1500,
    description: 'Un deslumbrante anillo solitario de diamante, una pieza central para cualquier ocasión.',
    image: PlaceHolderImages.find(p => p.id === 'product-ring-2')!,
    category: 'Rings',
    rating: 4,
    reviews: 155,
  },
  {
    id: '5',
    name: 'Collar de Gota',
    price: 1800,
    description: 'Un hermoso collar con un colgante en forma de gota de piedra lunar, engastado en plata de ley.',
    image: PlaceHolderImages.find(p => p.id === 'product-necklace-2')!,
    category: 'Necklaces',
    rating: 5,
    reviews: 98,
  },
  {
    id: '6',
    name: 'Broche de Hoja',
    price: 1500,
    description: 'Un broche de hoja natural preservada con detalles en oro rosa, una pieza de arte única.',
    image: PlaceHolderImages.find(p => p.id === 'product-earrings-2')!,
    category: 'Brooches',
    rating: 4,
    reviews: 76,
  },
];
