-- Create the collections table
CREATE TABLE collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  handle TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  sku TEXT UNIQUE,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create a junction table for the many-to-many relationship between collections and products
CREATE TABLE collection_products (
  collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  PRIMARY KEY (collection_id, product_id)
);

-- Enable Row Level Security for all tables
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE collection_products ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (read-only)
-- Allow public read access to collections
CREATE POLICY "Allow public read access to collections" ON collections FOR SELECT USING (true);

-- Allow public read access to products
CREATE POLICY "Allow public read access to products" ON products FOR SELECT USING (true);

-- Allow public read access to collection_products
CREATE POLICY "Allow public read access to collection_products" ON collection_products FOR SELECT USING (true);


-- Create policies for admin access (full control)
-- We will assume an 'admin' role exists or check custom claims in the future.
-- For now, let's create a placeholder policy that can be adapted.
-- To make this work, you would need to create a function that checks for an admin role.
-- Example function (requires a 'claims_admin' role in Supabase JWT):
--
-- CREATE OR REPLACE FUNCTION is_admin()
-- RETURNS boolean
-- LANGUAGE sql
-- STABLE
-- AS $$
--   SELECT 'admin' = get_my_claim('user_role');
-- $$;
--
-- Then policies would use `is_admin()`. For now, we'll restrict writes to authenticated users.

-- Allow full access for authenticated users (replace with admin role later)
CREATE POLICY "Allow full access for authenticated users" ON collections FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow full access for authenticated users" ON products FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow full access for authenticated users" ON collection_products FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');
