-- =================================================================
--  Glittershop Initial Schema
-- =================================================================

-- -----------------------------------------------------------------
--  1. Extensions
-- -----------------------------------------------------------------
-- Enable pgcrypto for UUID generation if not already enabled.
create extension if not exists "uuid-ossp" with schema "extensions";

-- -----------------------------------------------------------------
--  2. User Profiles and Roles
-- -----------------------------------------------------------------
-- Create a table for public user profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  email text unique,
  dob timestamp with time zone,
  role text default 'user' not null, -- 'user' or 'admin'
  updated_at timestamp with time zone default now()
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Policy: Profiles are viewable by everyone.
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

-- Policy: Users can insert their own profile.
create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

-- Policy: Users can update their own profile.
create policy "Users can update their own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- -----------------------------------------------------------------
--  3. Categories
-- -----------------------------------------------------------------
create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    created_at timestamp with time zone default now()
);

alter table public.categories enable row level security;

create policy "Categories are viewable by everyone."
  on public.categories for select
  using ( true );

-- -----------------------------------------------------------------
--  4. Collections
-- -----------------------------------------------------------------
create table if not exists public.collections (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    hero_image_url text,
    created_at timestamp with time zone default now()
);

alter table public.collections enable row level security;

create policy "Collections are viewable by everyone."
  on public.collections for select
  using ( true );

-- -----------------------------------------------------------------
--  5. Products
-- -----------------------------------------------------------------
create table if not exists public.products (
    id uuid primary key default uuid_generate_v4(),
    name text not null,
    description text,
    price numeric(10, 2) not null check (price >= 0),
    original_price numeric(10, 2) check (original_price >= 0),
    stock integer not null default 0 check (stock >= 0),
    
    -- Foreign Key to categories
    category_id bigint references public.categories(id),

    -- Product details
    materials text[],
    sizes text[],
    gems text[],
    dimensions text,
    care_instructions text,
    origin text,
    shipping_info text,

    -- Image
    image_url text,

    -- Ratings
    rating numeric(2, 1) default 0.0 check (rating >= 0 and rating <= 5),
    reviews_count integer default 0 check (reviews_count >= 0),
    
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

alter table public.products enable row level security;

create policy "Products are viewable by everyone."
  on public.products for select
  using ( true );

-- -----------------------------------------------------------------
--  6. Collection-Products Junction Table
-- -----------------------------------------------------------------
-- This table links products to collections (many-to-many relationship)
create table if not exists public.collection_products (
    collection_id bigint references public.collections(id) on delete cascade,
    product_id uuid references public.products(id) on delete cascade,
    primary key (collection_id, product_id)
);

alter table public.collection_products enable row level security;

create policy "Collection-product links are viewable by everyone."
  on public.collection_products for select
  using ( true );

-- -----------------------------------------------------------------
--  7. Automatically update `updated_at` timestamps
-- -----------------------------------------------------------------
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger for profiles
create trigger on_profile_update
  before update on public.profiles
  for each row execute procedure public.handle_updated_at();

-- Trigger for products
create trigger on_product_update
  before update on public.products
  for each row execute procedure public.handle_updated_at();


-- =================================================================
--  End of Schema
-- =================================================================
